apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
  - name: backend
    protocol: TCP
    port: 80
    targetPort: 8080
